CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(160) NOT NULL,
	`phone` varchar(30) NOT NULL,
	`email` varchar(320) NOT NULL,
	`insuranceType` enum('auto','sante','prevoyance') NOT NULL,
	`profile` varchar(160) NOT NULL,
	`postalCode` varchar(10) NOT NULL,
	`callbackPreference` varchar(120) NOT NULL,
	`message` text,
	`sourcePath` varchar(255) NOT NULL,
	`sourceKind` enum('seo','ads_form','ads_call','contact','homepage') NOT NULL,
	`utmSource` varchar(120),
	`utmMedium` varchar(120),
	`utmCampaign` varchar(160),
	`utmTerm` varchar(160),
	`utmContent` varchar(160),
	`status` enum('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',
	`ownerNotifiedAt` timestamp,
	`ownerEmailSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
